### ISSUE TITLE
Unable to open any menus while in game

### ISSUE THREAD

**Issue by xxT3R3Z1Xx** [LLA-Gaming/LS13#21]
Every SINGLE time I open LS13 on byond it'll stop responding for several seconds and I wont be able to select any options on the small window to join the game, I can join the game after maybe 15 minutes but  I still wont be able to open any menus in game.

I've tried a ton of solutions like clearing the byond cache, uninstalling and reinstalling byond several times, and disabling my antivirus firewalls.

If there are any known solutions that I haven't been able to find, I really want to know them.

**Comment by NullNeska** [comment]
Does this happen on any other server?

**Comment by xxT3R3Z1Xx** [comment]
All of the other popular ones, thoses are the only ones I've tried.

**Comment by NullNeska** [comment]
Might be a issue that is on your end that we cant really fix or debug.
